Fix empty `Tridiagonal` broadcast (#1324)
Fixes
```julia
julia> T = Tridiagonal(1:0, 1:0, 1:0)
0×0 Tridiagonal{Int64, UnitRange{Int64}}

julia> T .+ T
ERROR: ArgumentError: invalid GenericMemory size: the number of elements is either negative or too large for system address width
```
After this,
```julia
julia> T .+ T
0×0 Tridiagonal{Int64, Vector{Int64}}
```

The changes are minor, but the largish diff is because of adding a loop
to the tests, and additional indentation as a consequence.

(cherry picked from commit dccd6f810e4b69da91a208a57b1f796b4db31166)